import { TestBed } from '@angular/core/testing';
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { HttpClient, provideHttpClient } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';
import { ApiClient, API_BASE_URL, LoginRequest, LoginResponse } from './api.service';

/**
 * Story 21.7 — Unit tests for the NSwag-generated `ApiClient`.
 *
 * Pinning the request-shape contracts the rest of the app depends on:
 *   - URL composition / `API_BASE_URL` token wiring
 *   - HTTP method + headers + withCredentials per representative method
 *   - Error propagation through the generated `processX` pipeline
 *
 * IMPORTANT — do NOT edit `api.service.ts`; it is regenerated by
 * `npm run generate-api`. These tests assert against the shipped contract.
 */
describe('ApiClient', () => {
  let apiClient: ApiClient;
  let httpTesting: HttpTestingController;

  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [
        // Provider order matters per Angular HTTP testing docs:
        // provideHttpClient() MUST come before provideHttpClientTesting().
        provideHttpClient(),
        provideHttpClientTesting(),
        { provide: API_BASE_URL, useValue: '' },
      ],
    });

    apiClient = TestBed.inject(ApiClient);
    httpTesting = TestBed.inject(HttpTestingController);
  });

  afterEach(() => {
    httpTesting.verify();
    vi.restoreAllMocks();
  });

  // ---- AC-1 (first half) -----------------------------------------------------
  it('should be created (provided in root)', () => {
    expect(apiClient).toBeTruthy();
  });

  describe('without API_BASE_URL provider (constructor default)', () => {
    // ---- AC-1 (second half) -------------------------------------------------
    it('falls back to http://localhost:5292 when no API_BASE_URL is provided', () => {
      // Fresh TestBed with NO API_BASE_URL provider — the @Optional() ctor
      // parameter falls through to `baseUrl ?? "http://localhost:5292"`.
      TestBed.resetTestingModule();
      TestBed.configureTestingModule({
        providers: [provideHttpClient(), provideHttpClientTesting()],
      });

      const localHttp = TestBed.inject(HttpClient);
      const localHttpTesting = TestBed.inject(HttpTestingController);
      // Construct ApiClient directly with no baseUrl arg, mirroring the @Optional path.
      const localClient = new ApiClient(localHttp);

      localClient.auth_Login({ email: 'a@b.com', password: 'pw' } as LoginRequest).subscribe({
        // Avoid leaving an unhandled-error from the test backend tear-down.
        error: () => {},
      });

      const req = localHttpTesting.expectOne(
        'http://localhost:5292/api/v1/auth/login',
      );
      expect(req.request.method).toBe('POST');
      // Flush something so the test backend doesn't leave the request pending.
      // The generated client uses `responseType: 'blob'`, so the testing
      // backend requires a Blob (or `null`) — passing a raw string raises
      // "Automatic conversion to Blob is not supported for response type."
      req.flush(
        new Blob([JSON.stringify({ accessToken: 't', expiresIn: 3600 })], {
          type: 'application/json',
        }),
      );
      localHttpTesting.verify();
    });
  });

  // ===========================================================================
  // Task 2 — request-shape tests
  // ===========================================================================
  describe('request shape', () => {
    // ---- AC-2 ---------------------------------------------------------------
    it('auth_Login POSTs to /api/v1/auth/login with credentials and JSON headers', () => {
      apiClient
        .auth_Login({ email: 'a@b.com', password: 'pw' } as LoginRequest)
        .subscribe({ error: () => {} });

      const req = httpTesting.expectOne('/api/v1/auth/login');
      expect(req.request.method).toBe('POST');

      // NSwag stringifies the body itself, so the captured body is a JSON string.
      expect(typeof req.request.body).toBe('string');
      const parsed = JSON.parse(req.request.body as string);
      expect(parsed).toEqual({ email: 'a@b.com', password: 'pw' });

      expect(req.request.headers.get('Content-Type')).toBe('application/json');
      expect(req.request.headers.get('Accept')).toBe('application/json');
      expect(req.request.withCredentials).toBe(true);

      // Clean up — flush as Blob to match `responseType: 'blob'`.
      req.flush(
        new Blob([JSON.stringify({ accessToken: 't', expiresIn: 3600 })], {
          type: 'application/json',
        }),
      );
    });

    // ---- AC-3 ---------------------------------------------------------------
    it('auth_Login parses a 200 JSON-blob response into LoginResponse', async () => {
      const expected: LoginResponse = { accessToken: 't', expiresIn: 3600 } as LoginResponse;

      const promise = firstValueFrom(
        apiClient.auth_Login({ email: 'a@b.com', password: 'pw' } as LoginRequest),
      );

      const req = httpTesting.expectOne('/api/v1/auth/login');
      // The generated client requests `responseType: 'blob'`, so flushing a Blob
      // exercises the real `blobToText` -> JSON.parse pipeline.
      req.flush(
        new Blob([JSON.stringify(expected)], { type: 'application/json' }),
        { status: 200, statusText: 'OK' },
      );

      const result = await promise;
      expect(result.accessToken).toBe('t');
      expect(result.expiresIn).toBe(3600);
    });

    // ---- AC-4 ---------------------------------------------------------------
    it('auth_Login propagates a 401 as a thrown error preserving status', async () => {
      const errorPromise = firstValueFrom(
        apiClient.auth_Login({ email: 'a@b.com', password: 'wrong' } as LoginRequest),
      ).catch(e => e);

      const req = httpTesting.expectOne('/api/v1/auth/login');
      // Flush with a ProblemDetails-shaped body and 401 status — the generated
      // processAuth_Login matches `status === 401` and throws.
      req.flush(
        new Blob(
          [JSON.stringify({ type: '...', title: 'Unauthorized', status: 401, detail: 'bad creds' })],
          { type: 'application/json' },
        ),
        { status: 401, statusText: 'Unauthorized' },
      );

      const error = await errorPromise;
      expect(error).toBeDefined();
      // When NSwag's processX has a ProblemDetails result, throwException
      // throws the parsed `result` directly (so `status` is preserved on it).
      expect(error.status).toBe(401);
    });

    // ---- AC-5 ---------------------------------------------------------------
    it('auth_Refresh POSTs to /api/v1/auth/refresh with credentials and no Content-Type header', () => {
      apiClient.auth_Refresh().subscribe({ error: () => {} });

      const req = httpTesting.expectOne('/api/v1/auth/refresh');
      expect(req.request.method).toBe('POST');
      expect(req.request.withCredentials).toBe(true);
      expect(req.request.headers.get('Accept')).toBe('application/json');
      // The generated `auth_Refresh` builds an `HttpHeaders` with only `Accept`
      // (no body, no Content-Type) — pin the contract.
      expect(req.request.headers.has('Content-Type')).toBe(false);

      // Clean up — Blob to match `responseType: 'blob'`.
      req.flush(
        new Blob([JSON.stringify({ accessToken: 'new', expiresIn: 3600 })], {
          type: 'application/json',
        }),
      );
    });

    // ---- AC-6 ---------------------------------------------------------------
    it('dashboard_GetTotals appends ?year=<n> to the request URL', () => {
      apiClient.dashboard_GetTotals(2024).subscribe({ error: () => {} });

      const req = httpTesting.expectOne(
        r => r.urlWithParams === '/api/v1/dashboard/totals?year=2024',
      );
      expect(req.request.method).toBe('GET');
      expect(req.request.withCredentials).toBe(true);
      expect(req.request.headers.get('Accept')).toBe('application/json');

      // Clean up — Blob to match `responseType: 'blob'`.
      req.flush(new Blob([JSON.stringify({})], { type: 'application/json' }));
    });
  });

  // ===========================================================================
  // Task 3 — void/error path tests
  // ===========================================================================
  describe('error handling and void responses', () => {
    const expenseId = '00000000-0000-0000-0000-000000000001';

    // ---- AC-7 ---------------------------------------------------------------
    it('expenses_DeleteExpense issues DELETE and completes on 204 with no body', () => {
      let completed = false;
      let errored = false;
      apiClient.expenses_DeleteExpense(expenseId).subscribe({
        // NOTE: Avoid `firstValueFrom` here — the observable completes without
        // emitting on success, so `firstValueFrom` would reject with EmptyError.
        next: () => {},
        error: () => {
          errored = true;
        },
        complete: () => {
          completed = true;
        },
      });

      const req = httpTesting.expectOne(`/api/v1/expenses/${expenseId}`);
      expect(req.request.method).toBe('DELETE');
      expect(req.request.withCredentials).toBe(true);

      req.flush(null, { status: 204, statusText: 'No Content' });

      expect(errored).toBe(false);
      expect(completed).toBe(true);
    });

    // ---- AC-8 ---------------------------------------------------------------
    it('expenses_DeleteExpense rejects an unexpected 500 with status preserved and a "unexpected server error" message', async () => {
      const errorPromise = firstValueFrom(
        apiClient.expenses_DeleteExpense(expenseId),
        { defaultValue: undefined },
      ).catch(e => e);

      const req = httpTesting.expectOne(`/api/v1/expenses/${expenseId}`);
      req.flush(
        new Blob([JSON.stringify({ message: 'boom' })], { type: 'application/json' }),
        { status: 500, statusText: 'Internal Server Error' },
      );

      const error = await errorPromise;
      expect(error).toBeDefined();
      // 500 isn't in the handled list (200/204/401/404), so processX falls through
      // to the catch-all `throwException("An unexpected server error occurred.", ...)`
      // which constructs an `ApiException` (no parsed result) — message + status are surfaced.
      expect(error.status).toBe(500);
      expect(String(error.message)).toContain('An unexpected server error occurred.');
    });
  });
});
